### PR TITLE
add umd module output with inlined lodash dependency

### PR DESCRIPTION
**Pull request by gursharan001**
Hello, Thanks for the excellent and very useful library. 

We have lots of old style "namespaced" javascript code and would love to use this library.

Would you consider a PR to produce a UMD output of this module?

Thanks!

### CODE REVIEW

**Review by stevehanson — COMMENTED** [review]
Thanks for your contribution. I still haven't had a chance to review this, but could you remove the `azure-pipelines.yml` file? This project has CI set up with Circle. I just fixed the configuration so Circle also runs on forked PRs.

**Comment by gursharan001** [comment]
Thank! I have removed the azure pipelines file (added erroneously and was for a private build).

**Comment by stevehanson** [comment]
@gursharan001: I've put together an alternate PR, #85, to create UMD builds using Rollup. I went with Rollup instead of Microbundle since I was able to more easily find examples of other projects using Rollup. I'm going to close this PR in favor of the new one. Please take a look at #85 and let me know if it addresses your needs in that PR. Thanks again for your contribution.

**Comment by gursharan001** [comment]
Hi @stevehanson, thanks for adding this feature. I look forward to using the new version.

**Pull request closed without merging**
