### PR TITLE
Fix DeepPartial type #67

### PR DESCRIPTION
**Pull request by paulsouche**
This PR solves issue #67

### CODE REVIEW

**Comment by stevehanson** [comment]
Thank you for this PR. This will need to also have tests demonstrating the case that this solves. Additionally, this seems to fix a somewhat particular issue. Is there a broader issue that could be addressed with a broader fix? Thanks!

**Comment by paulsouche** [comment]
Hello ! I added 1 commit with a test that will fail to transpile if you change the DeepPartial signature. Let me know if ok for you.

Thanks again for the great job

**Comment by stevehanson** [comment]
Thanks again, @paulsouche. I've opened a PR that should cover this and some other issues with `DeepPartial`. Take a look and let me know if it looks like it will work for you: https://github.com/thoughtbot/fishery/pull/78.

**Comment by paulsouche** [comment]
Hello ! Yup ! It fixes my use case. Thanks a lot ! Closing this

**Pull request closed without merging**
