### PR TITLE
Modify DeepPartial to work with 'unknown' type

### LINKED ISSUE #29: DeepPartial type cannot handle 'unknown' type
Given the following example:
```typescript
import { Factory } from 'fishery';

interface Entity1 {
  entity2: Entity2;
}

interface Entity2 {
  id: string;
  entity3: Array<Entity3>;
}

interface Entity3 {
  _permissions: unknown;
}

const entity2Factory = Factory.define<Entity2>(() => ({
  id: 'abc',
  entity3: [],
}));

const entity2 = entity2Factory.build();

const entity1Factory = Factory.define<Entity1>(() => ({
  entity2: entity2Factory.build(),
}));

const entity1 = entity1Factory.build({
  entity2: entity2,
});
```

I receive the following TypeScript error:
```
TS2345: Argument of type '{ entity2: Entity2; }' is not assignable to parameter of type 'DeepPartial<Entity1>'.
   The types of 'entity2.entity3' are incompatible between these types.
      Type 'Entity3[]' is not assignable to type '(DeepPartial<Entity3> | undefined)[]'.
         Type 'Entity3' is not assignable to type 'DeepPartial<Entity3>'.
            Types of property '_permissions' are incompatible.
               Type 'unknown' is not assignable to type 'DeepPartial<unknown> | undefined'.
                  Type 'unknown' is not assignable to type 'DeepPartial<unknown>'.
```

### PR DESCRIPTION
**Pull request by b-houghton**
Fixes #29 

Credit for this fix goes to @OliverJAsh, who [wrote this to fix the same problem](https://github.com/reduxjs/redux/pull/3369/files#diff-b52768974e6bc0faccb7d4b75b162c99) in [reduxjs/redux](https://github.com/reduxjs/redux).

### CODE REVIEW

**Comment by stevehanson** [comment]
@b-houghton I just realized CI didn't run on this PR for some reason (maybe it's not running on forks). After I merged into master, I'm getting a test failure because this no longer compiles:

```typescript
// factory.test.ts:29
it('accepts partials of nested objects', () => {
  const user = userFactory.build({ address: { city: 'Ann Arbor' } }); // Compile error: Property state is missing but required in type { city: string, state: string }
  expect(user.address).toMatchObject({ city: 'Ann Arbor', state: 'MI' });
});
```

Basically, `DeepPartial` is no longer working for the type below and requiring a full `address` to be passed:

```typescript
type User = {
  id: string;
  name: string;
  address?: { city: string; state: string };
};
```

I can take a look later but curious if you have any thoughts. I might have to revert this till we get a fix.

**Comment by b-houghton** [comment]
@stevehanson Please forgive me; I'm not sure why this happened. I did run the tests before committing the change as the guidelines for contributing request. I may not have time to follow up on this this week, but will try to return to it by sometime early next week.

**Comment by stevehanson** [comment]
@b-houghton no worries! I reverted the PR for now, so there’s no rush. I’ll also try to take a look soon.

**Comment by b-houghton** [comment]
@stevehanson I have studied the TypeScript documentation and think I understand better what is happening. First, [the issue I reported](https://github.com/thoughtbot/fishery/issues/29) occurs because the type of `DeepPartial<unknown>` is incompatible with `unknown`. The [TypeScript release notes that introduce `unknown`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type) point out the type of a similar mapped type when the type parameter is `unknown`:

```
// Homomorphic mapped type over unknown

type T50<T> = { [P in keyof T]: number };
type T51 = T50<any>;  // { [x: string]: number }
type T52 = T50<unknown>;  // {}
```

Second, based on the error message that you pointed out, I think that the solution that I submitted in this PR fails because the condition `T[P] extends object` does not evaluate to `true` for the optional property `address`, because its type is `{city: string, state: string} | undefined`.

I have thought of two possible solutions. The first would recurse except when `T[P]` evaluates to `unknown` or `any`:
```typescript
export type DeepPartial<T> = { [P in keyof T]?: unknown extends T[P] ? T[P] : DeepPartial<T[P]> };
```

The other possible solution extends the present one by allowing for optional object properties:
```typescript
export type DeepPartial<T> = { [P in keyof T]?: T[P] extends object | undefined ? DeepPartial<T[P]> : T[P] };
```

Based on the [TypeScript documentation for distributive conditional types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types), `T[P] extends object | undefined` will evaluate to true both for properties that are assignable to type `object` and properties that that are assignable to type `undefined`. I don't think allowing the latter would have any negative effect given that the current implementation of `DeepPartial` recurses for all types, including `undefined`.

What do you think of these possibilities?

**Comment by stevehanson** [comment]
@b-houghton this is awesome. Thanks for putting so much thought and research into this, and good find that the error was because the address was typed as `object | undefined`.

I really like your first solution because it explicitly only changes our current implementation for the `unknown` case we're trying to solve for.

The second option fixes the case where the object could be undefined, like in our tests, but would it work for `object | null` or `object | string`, etc?

**Comment by b-houghton** [comment]
@stevehanson I'm glad you asked. Upon investigation, the answer is no. I had thought, based on the [documentation for distributive conditional types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#distributive-conditional-types), that it would work, but it doesn't. I admittedly don't yet understand why. Regardless, it looks like the first solution I proposed is the only viable one of the two. Shall I open a new PR for it?

**Comment by stevehanson** [comment]
@b-houghton yeah, that'd be great! I should be able to review it sometime this week. Thanks again!

**Pull request merged**
